In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("C:/Users/jaymk/Downloads/enhanced_mental_health_dataset.csv")
data.head()

,Heart_Rate_BPM,Sleep_Duration_Hours,Physical_Activity_Steps,Mood_Rating,Mental_Health_Condition,Age,Gender,Family_History,Social_Media_Usage_Hours,Survey_Sentiment_Score,Work_Interference
0,98,7.425124,13760,5,1,56,Male,No,0.17,0.43,Never
1,111,9.457572,11455,9,0,46,Female,Yes,2.88,-0.17,Never
2,88,4.037103,9174,8,1,32,Female,Yes,7.12,-0.61,Often
3,74,8.864101,12612,1,1,60,Female,Yes,5.52,0.50,Sometimes
4,102,9.690217,3923,9,0,25,Female,Yes,1.16,0.62,Rarely